<a href="https://colab.research.google.com/github/Suriya-Panneerselvam/SeedClassification/blob/main/seed.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
from sklearn.metrics import accuracy_score,confusion_matrix, classification_report
import numpy as np
import pickle

#importing data
data=pd.read_csv('/content/drive/MyDrive/seeds (1).csv')
data.head()

#spliting the data
x=data.iloc[:,0:7]
y=data.iloc[:,-1]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30)

#decision tree
model=DecisionTreeClassifier()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
model_accuracy=accuracy_score(y_test,y_pred)
print ('The accuracy score of decision tree:',model_accuracy)

#confusion matrics
print('The confusion metrics of data:\n',confusion_matrix(y_test,y_pred))

#confusion matrics accuracy score
metrics_accuracy=metrics.accuracy_score(y_test,y_pred)
print('The accuracy score of confusion metrics:',metrics_accuracy)

#classification report
print('The classification report of data:\n',classification_report(y_test,y_pred))

#softwere convertion
with open('seed.pkl','wb') as file:
    pickle.dump(model,file)
with open('seed.pkl','rb') as file:
    model=pickle.load(file)

#testing the model
Area=int(input("Enter Area value:"))
Perimeter=int(input('Enter Perimeter value:'))
Compactness=int(input('Enter Compactness value:'))
Kernel_Length=int(input('Enter Kernel Length value:'))
Kernel_Width=int(input('Enter Kernel Width value:'))
Asymmetry_Coeff=float(input('Enter Asymmetry Coeff value:'))
Kernel_Groove=float(input('Enter Kernel Groove value:'))

input=np.array([[Area,Perimeter,Compactness,Kernel_Length,Kernel_Width,Asymmetry_Coeff,Kernel_Groove]])

prediction=model.predict(input)

#final prediction output
print('The prediction:',prediction)
if prediction==1:
    print('The seed is type 1')
elif prediction==2:
    print('The seed is type 2')
else:
    print('The seed is type 3')

The accuracy score of decision tree: 0.8833333333333333
The confusion metrics of data:
 [[15  1  3]
 [ 0 21  0]
 [ 3  0 17]]
The accuracy score of confusion metrics: 0.8833333333333333
The classification report of data:
               precision    recall  f1-score   support

           1       0.83      0.79      0.81        19
           2       0.95      1.00      0.98        21
           3       0.85      0.85      0.85        20

    accuracy                           0.88        60
   macro avg       0.88      0.88      0.88        60
weighted avg       0.88      0.88      0.88        60

Enter Area value:88
Enter Perimeter value:56
Enter Compactness value:76
Enter Kernel Length value:87
Enter Kernel Width value:56
Enter Asymmetry Coeff value:38
Enter Kernel Groove value:97
The prediction: [2]
The seed is type 2


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
